# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

# ebuild partially generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal git-r3

DESCRIPTION="Accelerate backend generating LLVM"
HOMEPAGE="http://hackage.haskell.org/package/accelerate-llvm-native"
EGIT_REPO_URI="https://github.com/AccelerateHS/accelerate-llvm.git"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS=""
IUSE="+bounds-checks debug internal-checks unsafe-checks"

RDEPEND=">=dev-haskell/accelerate-9999:=[profile?, bounds-checks?, debug?, internal-checks?, unsafe-checks?]
	>=dev-haskell/accelerate-llvm-9999:=[profile?, bounds-checks?, debug?, internal-checks?, unsafe-checks?]
	>=dev-haskell/dlist-0.6:=[profile?]
	>=dev-haskell/fclabels-2.0:=[profile?]
	>=dev-haskell/libffi-0.1:=[profile?]
	>=dev-haskell/llvm-general-3.2:=[profile?]
	>=dev-haskell/llvm-general-pure-3.2:=[profile?]
	>=dev-haskell/mtl-2.2.1:=[profile?]
	>=dev-haskell/vector-0.10:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag bounds-checks bounds-checks) \
		$(cabal_flag debug debug) \
		$(cabal_flag internal-checks internal-checks) \
		$(cabal_flag unsafe-checks unsafe-checks)
}
