EAPI=6

# ebuild partially generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal git-r3

DESCRIPTION="a library to allow easy interoperation between Repa and HMatrix"
HOMEPAGE="https://github.com/dlahoti/repa-hmatrix"
EGIT_REPO_URI="https://github.com/dlahoti/repa-hmatrix.git"

LICENSE="GPL-3"
SLOT="0/${PV}"
KEYWORDS=""
IUSE=""

RDEPEND="dev-haskell/hmatrix:=[profile?]
	dev-haskell/repa:=[profile?]
	dev-haskell/vector:=[profile?]
	>=dev-lang/ghc-7.10.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.2.0
"
