# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

# ebuild generated by hackport 0.4.7.9999
#hackport: flags: have-gio:gio,-have-quartz-gtk

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit git-r3 haskell-cabal

DESCRIPTION="Binding to the Gtk+ graphical user interface library"
HOMEPAGE="http://projects.haskell.org/gtk2hs/"
EGIT_REPO_URI="https://github.com/gtk2hs/gtk2hs/"

LICENSE="LGPL-2.1"
SLOT="2/${PV}"
KEYWORDS="~alpha ~amd64 ~ia64 ~ppc ~ppc64 ~sparc ~x86"
IUSE="+deprecated +fmode-binary +gio"

S="${S}/${PN}"

RDEPEND=">=dev-haskell/cairo-9999:=[profile?]
	>=dev-haskell/glib-9999:=[profile?]
	dev-haskell/mtl:=[profile?]
	>=dev-haskell/pango-9999:=[profile?]
	>=dev-haskell/text-0.11.0.6:=[profile?] <dev-haskell/text-1.3:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	dev-libs/glib:2
	x11-libs/gtk+:2
	gio? ( >=dev-haskell/gio-9999:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18
	>=dev-haskell/gtk2hs-buildtools-9999
	virtual/pkgconfig
"

src_prepare() {
	default

	rm "${S}/gtk3.cabal"
	mv "${S}/gtk.cabal-renamed" "${S}/gtk.cabal"
}

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag deprecated deprecated) \
		$(cabal_flag fmode-binary fmode-binary) \
		$(cabal_flag gio have-gio) \
		--flag=-have-quartz-gtk
}
