# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

# ebuild generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Perform fft with repa via FFTW"
HOMEPAGE="http://hackage.haskell.org/package/repa-fftw"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/carray-0.1.5:=[profile?]
	>=dev-haskell/fft-0.1.5:=[profile?]
	>=dev-haskell/repa-3.2.3:=[profile?]
	>=dev-haskell/storable-complex-0.2:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	test? ( >=dev-haskell/tasty-0.4.0
		>=dev-haskell/tasty-hunit-0.4.1
		>=dev-haskell/tasty-quickcheck-0.3.1 )
"
