# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=5

# ebuild partially generated by hackport 0.4.3

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal git-r3

DESCRIPTION="High performance, regular, shape polymorphic parallel arrays"
HOMEPAGE="http://repa.ouroborus.net"
EGIT_REPO_URI="https://github.com/dlahoti/repa.git"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

S="${S}/${PN}"

RDEPEND=">=dev-haskell/quickcheck-2.7:2=[profile?]
	>=dev-haskell/vector-0.10:=[profile?] <dev-haskell/vector-0.11:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"

src_prepare() {
	cabal_chdeps \
		'QuickCheck           == 2.8.*' 'QuickCheck           >= 2.8'
}
