# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

# ebuild partially generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit git-r3 haskell-cabal

DESCRIPTION="Haskell bindings for the wlc Wayland compositor library"
HOMEPAGE="https://github.com/dlahoti/haskell-wlc"
EGIT_REPO_URI="https://github.com/dlahoti/haskell-wlc.git"

LICENSE="GPL-3"
SLOT="0/${PV}"
KEYWORDS=""
IUSE=""

RDEPEND="dev-haskell/data-default:=[profile?]
	>=dev-lang/ghc-7.10.1:=
	dev-libs/wlc
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.2.0
	virtual/pkgconfig
"
