# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

# ebuild partially generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal git-r3

DESCRIPTION="Accelerate backend generating LLVM"
HOMEPAGE="http://hackage.haskell.org/package/accelerate-llvm"
EGIT_REPO_URI="https://github.com/AccelerateHS/accelerate-llvm.git"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS=""
IUSE="+bounds-checks +chase-lev debug internal-checks unsafe-checks"

S="${S}/${PN}"

RDEPEND=">=dev-haskell/abstract-deque-0.3:=[profile?]
	=dev-haskell/accelerate-9999:=[profile?, bounds-checks?, debug?, internal-checks?, unsafe-checks?]
	>=dev-haskell/data-default-class-0.0.1:=[profile?]
	>=dev-haskell/dlist-0.6:=[profile?]
	>=dev-haskell/exceptions-0.6:=[profile?]
	>=dev-haskell/fclabels-2.0:=[profile?]
	>=dev-haskell/llvm-general-3.2:=[profile?]
	>=dev-haskell/llvm-general-pure-3.2:=[profile?]
	>=dev-haskell/mtl-2.0:=[profile?]
	>=dev-haskell/mwc-random-0.13:=[profile?]
	>=dev-haskell/unordered-containers-0.2:=[profile?]
	>=dev-haskell/vector-0.10:=[profile?]
	>=dev-lang/ghc-7.8.2:=
	chase-lev? ( >=dev-haskell/chaselev-deque-0.5:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag bounds-checks bounds-checks) \
		$(cabal_flag chase-lev chase-lev) \
		$(cabal_flag debug debug) \
		$(cabal_flag internal-checks internal-checks) \
		$(cabal_flag unsafe-checks unsafe-checks)
}
