EAPI=6

# ebuild (partially) generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="X11-rm"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A binding to the resource management functions missing from X11"
HOMEPAGE="http://hackage.haskell.org/package/X11-rm"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/x11:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	dev-haskell/cabal
"

S="${WORKDIR}/${MY_P}"

src_prepare() {
	mv "${S}/Setup.hs" "${S}/Setup.lhs" || die

	eapply_user
}
