# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

# ebuild partially generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Human friendly BLAS and Lapack bindings for Haskell"
HOMEPAGE="https://github.com/wellposed/hblas/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/primitive-0.5:=[profile?]
	>=dev-haskell/storable-complex-0.2.0:=[profile?]
	dev-haskell/vector:=[profile?]
	>=dev-lang/ghc-7.6.1:=
	virtual/cblas
	virtual/blas
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	test? ( >=dev-haskell/hunit-1.2.5 <dev-haskell/hunit-1.3
		>=dev-haskell/tasty-0.8 <dev-haskell/tasty-0.9
		>=dev-haskell/tasty-hunit-0.8 <dev-haskell/tasty-hunit-0.9
		>=dev-haskell/vector-0.5 <dev-haskell/vector-0.12 )
"

src_prepare() {
	sed -i -e 's:storable-complex .*:storable-complex:' "${S}/${PN}.cabal"
	sed -i -e 's:primitive .*:primitive:' "${S}/${PN}.cabal"

	eapply_user
}

src_configure() {
	haskell-cabal_src_configure \
		-fcblas
}
