# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=5

# ebuild generated by hackport 0.4.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal git-r3

DESCRIPTION="Haskell bindings for libxkbcommon"
HOMEPAGE="https://github.com/dlahoti/haskell-xkbcommon"
EGIT_REPO_URI="https://github.com/dlahoti/haskell-xkbcommon.git"
EGIT_BRANCH="patch-1"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/cpphs:=[profile?]
	dev-haskell/data-flags:=[profile?]
	dev-haskell/storable-record:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/transformers:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	x11-libs/libxkbcommon
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"
